name: Tests (Linux)
on: [push]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-24.04
          #- windows-latest
        dc:
          - dmd-latest
          - dmd-2.110.0
          - ldc-latest
          - ldc-1.40.0
        buildConf:
          - Static
          - Dynamic

    env:
      POSTGRES_USER: peque
      POSTGRES_PASSWORD: peque
      POSTGRES_DB: peque-test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: peque
          POSTGRES_PASSWORD: peque
          POSTGRES_DB: peque-test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}

      - name: Try to build the lib
        run: dub build -c "library${{ matrix.buildConf }}"

      - name: Try to build the lib
        run: dub build -c "library${{ matrix.buildConf }}"

      - name: Run tests
        run: dub test -b unittest-cov -c "unittest${{ matrix.buildConf }}"
