name: Tests
on: [push]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          #- windows-latest
        dc:
          - dmd-latest
          - dmd-2.109.1
          - ldc-latest
          - ldc-1.40.0
        buildConf:
          - Static
          - Dynamic
        include:
          - os: macOS-latest
            dc: ldc-1.40.0
            buildConf: Dynamic
          - os: macOS-latest
            dc: ldc-1.40.0
            buildConf: Static
    env:                               
      DEBIAN_FRONTEND: 'noninteractive'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Update apt registry
        run: apt-get update

      - name: Install system dependencies (postgresql)
        run: apt-get install --no-install-recommends -yq postgresql sudo

      - name: Start postgresql
        run: /etc/init.d/postgresql start

      - name: Create postgresql user
        run: |
          sudo -u postgres -H createuser "peque"
          sudo -u postgres -H psql -c "ALTER USER peque WITH PASSWORD 'peque'"
      
      - name: Try to build the lib
        run: dub build -c "library${{ matrix.buildConf }}"

      - name: Try to build the lib
        run: dub build -c "library${{ matrix.buildConf }}"

      - name: Run tests
        run: dub test -b unittest-cov -c "unittest${{ matrix.buildConf }}"
