name: Tests
on: [push]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04
          #- windows-latest
        dc:
          - dmd-latest
          - dmd-2.109.1
          - ldc-latest
          - ldc-1.40.0
        include:
          - os: macOS-latest
            dc: ldc-1.40.0

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install system dependencies                                           
        uses: lyricwulf/abc@v1                                                      
        with:                                                                                  
          linux: libpq-dev
          macos: libpq

      - name: Run tests
        run: dub test -b unittest-cov
